version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: medods_db
      TZ: 'Europe/Moscow'
    volumes:
      - ./migrations/0001_create_refresh_token_table.sql:/docker-entrypoint-initdb.d/0001_create_refresh_token_table.sql
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d medods_db']
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_USER: postgres
      DB_PASSWORD: 12345
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: medods_db

      PORT: '3000'
      TZ: 'Europe/Moscow'
    ports:
      - '3000:3000'

volumes:
  pgdata:
